### ISSUE TITLE
Upgrade python version to 3.12

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/aced_etl_pod#17]
As an ACED user, when I'm submitting jobs, it would be useful to have quick response time.

https://github.com/ACED-IDP/aced_etl_pod/blob/main/etl-job/Dockerfile#L2

Can we update to 3.12 and test.

**Comment by matthewpeterkort** [comment]
https://github.com/ACED-IDP/aced_etl_pod/commit/5b63db50c40326de23c9afcb34f781f6f64d3eb1

**Comment by bwalsh** [comment]
@matthewpeterkort if all is complete with 3.12 upgrade, can you close this issue?
