### ISSUE TITLE
Return stack trace if any exception

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/aced_etl_pod#22]
* stack trace should be added to logs here:  https://github.com/ACED-IDP/aced_etl_pod/blob/development/etl-job/fhir_import_export.py#L248
* do not log LOADED message here: https://github.com/ACED-IDP/aced_etl_pod/blob/development/etl-job/fhir_import_export.py#L249

**Comment by matthewpeterkort** [comment]
> * stack trace should be added to logs here:  https://github.com/ACED-IDP/aced_etl_pod/blob/development/etl-job/fhir_import_export.py#L248
> 

Seems like the above issue has been resolved here: https://github.com/ACED-IDP/aced_etl_pod/blob/feature/empty-project/etl-job/fhir_import_export.py#L347

>     * do not log LOADED message here: https://github.com/ACED-IDP/aced_etl_pod/blob/development/etl-job/fhir_import_export.py#L249

Not sure what the above issue is referring to.
