### ISSUE TITLE
Add option to `delete all`  in project

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/aced_etl_pod#23]
Add --delete-content flag to `put` job.

If selected, issue the following commands:

``` 
for table_name in reverse_dependency__order:
   delete from {table_name}  where _props->>'project_id' = '{project_id}' ;
```

See https://github.com/bmeg/iceberg-schema-tools/blob/1c354e2de6868f3f0d27421a7093e10d6bc81298/config.yaml#L6

**Comment by matthewpeterkort** [comment]
This seems to have been added here: 
https://github.com/ACED-IDP/submission/blob/feature/empty-project/aced_submission/meta_graph_load.py#L361

Just not in reverse order.
